
package publicador;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://publicador/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    publicador.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns publicador.DtPostulacionCompleto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getPostulanteDeOfertaRequest", output = "http://publicador/WebServices/getPostulanteDeOfertaResponse")
    public DtPostulacionCompleto getPostulanteDeOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/cambiarEstadoOfertaRequest", output = "http://publicador/WebServices/cambiarEstadoOfertaResponse")
    public void cambiarEstadoOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        EstadoOferta arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/ingresarOfertaLaboralRequest", output = "http://publicador/WebServices/ingresarOfertaLaboralResponse")
    public void ingresarOfertaLaboral(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        float arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        StringArray arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        EstadoOferta arg11);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtTipoDeOferta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/mostrarTipoOfertaRequest", output = "http://publicador/WebServices/mostrarTipoOfertaResponse")
    public DtTipoDeOferta mostrarTipoOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicador.DtPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getDtPaquetesRequest", output = "http://publicador/WebServices/getDtPaquetesResponse")
    public DtPaqueteArray getDtPaquetes();

    /**
     * 
     * @return
     *     returns publicador.DtOfertaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarOfertasSinOrdenarRequest", output = "http://publicador/WebServices/listarOfertasSinOrdenarResponse")
    public DtOfertaArray listarOfertasSinOrdenar();

    /**
     * 
     * @return
     *     returns publicador.DtOfertaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarOfertasRequest", output = "http://publicador/WebServices/listarOfertasResponse")
    public DtOfertaArray listarOfertas();

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtPostulanteCompleto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/mostrarPostulanteRequest", output = "http://publicador/WebServices/mostrarPostulanteResponse")
    public DtPostulanteCompleto mostrarPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtEmpresaCompleto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/mostrarEmpresaRequest", output = "http://publicador/WebServices/mostrarEmpresaResponse")
    public DtEmpresaCompleto mostrarEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/estaPostuladoRequest", output = "http://publicador/WebServices/estaPostuladoResponse")
    public boolean estaPostulado(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/obtenerPaquetesRequest", output = "http://publicador/WebServices/obtenerPaquetesResponse")
    public StringArray obtenerPaquetes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/ofertaDeEmpresaRequest", output = "http://publicador/WebServices/ofertaDeEmpresaResponse")
    public boolean ofertaDeEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns publicador.DtUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getDtUsuariosRequest", output = "http://publicador/WebServices/getDtUsuariosResponse")
    public DtUsuarioArray getDtUsuarios();

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/setFollowRequest", output = "http://publicador/WebServices/setFollowResponse")
    public void setFollow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/setUnFollowRequest", output = "http://publicador/WebServices/setUnFollowResponse")
    public void setUnFollow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarEmpresaAutoCompletarRequest", output = "http://publicador/WebServices/listarEmpresaAutoCompletarResponse")
    public StringArray listarEmpresaAutoCompletar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getDtUsuarioRequest", output = "http://publicador/WebServices/getDtUsuarioResponse")
    public DtUsuario getDtUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/unicoRequest", output = "http://publicador/WebServices/unicoResponse")
    public String unico(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtOfertaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarOfertasPorKeywordRequest", output = "http://publicador/WebServices/listarOfertasPorKeywordResponse")
    public DtOfertaArray listarOfertasPorKeyword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/comprarPaqueteRequest", output = "http://publicador/WebServices/comprarPaqueteResponse")
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/tienePaqueteRequest", output = "http://publicador/WebServices/tienePaqueteResponse")
    public boolean tienePaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg12
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/ingresarOfertaLaboralConPaqueteRequest", output = "http://publicador/WebServices/ingresarOfertaLaboralConPaqueteResponse")
    public void ingresarOfertaLaboralConPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        float arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        StringArray arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11,
        @WebParam(name = "arg12", partName = "arg12")
        EstadoOferta arg12);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/addVisitaRequest", output = "http://publicador/WebServices/addVisitaResponse")
    public void addVisita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/addOfertaFavoritoRequest", output = "http://publicador/WebServices/addOfertaFavoritoResponse")
    public void addOfertaFavorito(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/removeOfertaFavoritoRequest", output = "http://publicador/WebServices/removeOfertaFavoritoResponse")
    public void removeOfertaFavorito(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getReputacionOfertaRequest", output = "http://publicador/WebServices/getReputacionOfertaResponse")
    public int getReputacionOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/tienePostulanteFavoritoRequest", output = "http://publicador/WebServices/tienePostulanteFavoritoResponse")
    public boolean tienePostulanteFavorito(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/cargarOrdenAPostRequest", output = "http://publicador/WebServices/cargarOrdenAPostResponse")
    public void cargarOrdenAPost(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/finalizarSeleccionRequest", output = "http://publicador/WebServices/finalizarSeleccionResponse")
    public void finalizarSeleccion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/seleccionFinalizadaRequest", output = "http://publicador/WebServices/seleccionFinalizadaResponse")
    public boolean seleccionFinalizada(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/limpiarOrdenRequest", output = "http://publicador/WebServices/limpiarOrdenResponse")
    public void limpiarOrden(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/existeNicknameRequest", output = "http://publicador/WebServices/existeNicknameResponse")
    public boolean existeNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/existeEmailRequest", output = "http://publicador/WebServices/existeEmailResponse")
    public boolean existeEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/existeOfertaRequest", output = "http://publicador/WebServices/existeOfertaResponse")
    public boolean existeOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws IOException_Exception
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/guardarImagenRequest", output = "http://publicador/WebServices/guardarImagenResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://publicador/WebServices/guardarImagen/Fault/IOException")
    })
    public void guardarImagen(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws IOException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param fileName
     * @return
     *     returns byte[]
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getFileRequest", output = "http://publicador/WebServices/getFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://publicador/WebServices/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "fileName", partName = "fileName")
        String fileName,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarTipoDeOfertaRequest", output = "http://publicador/WebServices/listarTipoDeOfertaResponse")
    public StringArray listarTipoDeOferta();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarKeywordsRequest", output = "http://publicador/WebServices/listarKeywordsResponse")
    public StringArray listarKeywords();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/ingresarPostulanteRequest", output = "http://publicador/WebServices/ingresarPostulanteResponse")
    public void ingresarPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/ingresarEmpresaRequest", output = "http://publicador/WebServices/ingresarEmpresaResponse")
    public void ingresarEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtOfertaCompleto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/mostrarOfertaCompletoRequest", output = "http://publicador/WebServices/mostrarOfertaCompletoResponse")
    public DtOfertaCompleto mostrarOfertaCompleto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/esEmpresaRequest", output = "http://publicador/WebServices/esEmpresaResponse")
    public boolean esEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/modificarDatosEmpresaRequest", output = "http://publicador/WebServices/modificarDatosEmpresaResponse")
    public void modificarDatosEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/esPostulanteRequest", output = "http://publicador/WebServices/esPostulanteResponse")
    public boolean esPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/modificarDatosPostulanteRequest", output = "http://publicador/WebServices/modificarDatosPostulanteResponse")
    public void modificarDatosPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     */
    @WebMethod
    @Action(input = "http://publicador/WebServices/postularRequest", output = "http://publicador/WebServices/postularResponse")
    public void postular(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns publicador.DtOfertaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/listarOfertasPorEmpresaRequest", output = "http://publicador/WebServices/listarOfertasPorEmpresaResponse")
    public DtOfertaArray listarOfertasPorEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        EstadoOferta arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtOferta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/mostrarOfertaRequest", output = "http://publicador/WebServices/mostrarOfertaResponse")
    public DtOferta mostrarOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicador.DtPaqueteCompleto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicador/WebServices/getDtPaqueteCompletoRequest", output = "http://publicador/WebServices/getDtPaqueteCompletoResponse")
    public DtPaqueteCompleto getDtPaqueteCompleto(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
